packages:
  - 'apps/*'
  - 'shared/**'

catalogs:
  common:
    'lodash-es': '^4.17.21'
    '@types/lodash-es': '^4.17.12'
    '@types/node': '^22.14.0'
    'tsx': '^4.19.3'
    'glob': '^11.0.3'
    'dayjs': '^1.11.13'

  ui:
    'vue': '^3.5.13'
    'vue-tsc': '^2.2.8'
    '@vitejs/plugin-vue': '^5.2.3'
    'element-plus': '^2.9.11'
    'openapi-typescript': '^7.6.1'
    'vite': '^6.2.4'
    'zod': '^3.25.34'
    'vee-validate': '^4.15.0'
    '@vee-validate/zod': '^4.15.0'
    'vue-component-type-helpers': '^2.2.10'
    'vue-i18n': '^11.1.3'
    '@intlify/unplugin-vue-i18n': '^6.0.5'

  api:
    '@nestjs/common': '^11.0.1'
    '@nestjs/swagger': '^11.1.4'
    'class-transformer': '^0.5.1'
    'class-validator': '^0.14.1'
    '@nestjs/core': '^11.0.1'
    '@types/express': '^5.0.1'
    'express': '^5.1.0'
    '@nestjs/platform-express': '^11.0.1'
    'rxjs': '^7.8.1'
    'nestjs-i18n': '^10.5.1'
    '@types/jest': '^29.5.14'
    'jest': '^29.7.0'
    'ts-jest': '^29.2.5'
    '@prisma/client': '^6.10.1'
    'prisma': '^6.10.1'
    'redis': '^4.7.0'
    '@redis/client': '^1.6.0'
    '@nestjs/config': '^4.0.2'
