packages:
  - apps/*
  - shared/**

catalogs:
  common:
    filesize: ^10.1.6
    mime: ^4.0.7
    lodash-es: ^4.17.21
    '@types/lodash-es': ^4.17.12
    '@types/node': ^22.14.0
    tsx: ^4.19.3
    glob: ^11.0.3
    dayjs: ^1.11.13
    typescript: ^5.8.3
  ui:
    vue: ^3.5.17
    vue-tsc: ^2.2.8
    vite: ^7.0.0
    '@vitejs/plugin-vue': ^6.0.0
    '@vitejs/plugin-vue-jsx': ^5.0.0
    '@vitest/eslint-plugin': ^1.2.7
    vite-plugin-dts: ^4.5.4
    element-plus: 2.10.3
    'unplugin-element-plus': '^0.9.1'
    '@element-plus/icons-vue': ^2.3.1
    openapi-typescript: ^7.6.1
    zod: ^3.25.34
    vee-validate: ^4.15.0
    '@vee-validate/zod': ^4.15.0
    vue-component-type-helpers: ^2.2.10
    vue-i18n: ^11.1.3
    '@intlify/unplugin-vue-i18n': ^6.0.5
    '@tailwindcss/vite': '^4.1.10'
    tailwindcss: ^4.1.10
    '@vueuse/core': ^13.4.0
    vue-router: ^4.5.1
    vite-svg-loader: ^5.1.0
  api:
    '@nestjs/common': ^11.0.1
    '@nestjs/swagger': ^11.1.4
    class-transformer: ^0.5.1
    class-validator: ^0.14.1
    '@nestjs/core': ^11.0.1
    '@types/express': ^5.0.1
    express: ^5.1.0
    '@nestjs/platform-express': ^11.0.1
    rxjs: ^7.8.1
    nestjs-i18n: ^10.5.1
    '@types/jest': ^29.5.14
    jest: ^29.7.0
    ts-jest: ^29.2.5
    '@prisma/client': ^6.10.1
    prisma: ^6.10.1
    redis: ^4.7.0
    '@redis/client': ^1.6.0
    '@nestjs/config': ^4.0.2
